version: '3.4'

services:

  nadinsoftDb:
    container_name: nadinsotDb
    environment:
        SA_PASSWORD: "12MoaceEA"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "5666:1433"
    volumes:
      - "nadinsoftDb_data:/var/opt/mssql/data"
      - "nadinsoftDb_log:/var/opt/mssql/log"
      - "nadinsoftDb_secrets:/var/opt/mssql/secrets"

  nadinsoft.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "5032:80"
    #depends_on:
    #  - nadinsoftDb