version: '3.4'

services:

  nadinsoftDb:
    container_name: nadinsotDb
    environment:
        MSSQL_SA_PASSWORD: "12MoaceEA"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1401:1433"
    volumes:
      - "nadinsoftDb_volume:/var/opt/mssql"

  nadinsoft.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "5121:80"
    depends_on:
      - nadinsoftDb